name = "wl_lib"
description = "Handy library packages"
version = "0.1.3"
licenses= "GPL-3.0-or-later"

authors = ["Fraser Wilson"]
maintainers = ["Fraser Wilson <fraser@thewhitelion.eu>"]
maintainers-logins = ["blancolioni"]
tags = ["miscellanea", "utility"]
website = "https://github.com/blancolioni/wl_lib"
